version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_audifonos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1007
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # IMPORTANTE: no pongas el volumen persistente hasta después de la carga inicial

  flask:
    build: .
    container_name: flask_audifonos
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1007
      DB_NAME: tienda_audifonos
    ports:
      - "5000:5000"
